import { ReactComponent as AstronateFirst } from "../src/Assets/Astronaut1.svg";
import { ReactComponent as AstronateSecond } from "../src/Assets/Astronaut2.svg";
import '././page/styles.css';

export const dataArray = [
  {
    id: 1,
    photo: 'astronaut1',
    content: "Content 1",
    status: "Scheduled",
    username: "User1",
    createdDate: "2022-01-01",
    value: "Regenerate",
  },
  {
    id: 2,
    photo: 'astronaut1',
    content: "Content 2",
    status: "Scheduled",
    username: "User2",
    createdDate: "2022-01-02",
    value: "Generate",
  },
  {
    id: 3,
    photo: 'astronaut1',
    content: "Content 3",
    status: "Scheduled",
    username: "User3",
    createdDate: "2022-01-03",
    value: "Regenerate",
  },
  {
    id: 4,
    photo: 'astronaut2',
    content: "Content 4",
    status: "Scheduled",
    username: "User4",
    createdDate: "2022-01-03",
    value: "Regenerate",
  },
  {
    id: 5,
    photo: 'astronaut1',
    content: "Content 5",
    status: "Scheduled",
    username: "User5",
    createdDate: "2022-01-03",
    value: "Regenerate",
  },
  {
    id: 6,
    photo: 'astronaut2',
    content: "Content 6",
    status: "Scheduled",
    username: "User6",
    createdDate: "2022-01-03",
    value: "Generate",
  },
  {
    id: 7,
    photo: 'astronaut1',
    content: "Content 7",
    status: "Scheduled",
    username: "User7",
    createdDate: "2022-01-03",
    value: "Regenerate",
  },
  {
    id: 8,
    photo: 'astronaut2',
    content: "Content 8",
    status: "Scheduled",
    username: "User8",
    createdDate: "2022-01-03",
    value: "Generate",
  },
  {
    id: 9,
    photo: 'astronaut1',
    content: "Content 9",
    status: "Scheduled",
    username: "User9",
    createdDate: "2022-01-03",
    value: "Generate",
  },
  {
    id: 10,
    photo: 'astronaut2',
    content: "Content 10",
    status: "Scheduled",
    username: "User10",
    createdDate: "2022-01-03",
    value: "Regenerate",
  },
  {
    id: 11,
    photo: 'astronaut1',
    content: "Content 11",
    status: "Scheduled",
    username: "User11",
    createdDate: "2022-01-03",
    value: "Generate",
  },
  {
    id: 12,
    photo: 'astronaut2',
    content: "Content 12",
    status: "Scheduled",
    username: "User12",
    createdDate: "2022-01-03",
    value: "Regenerate",
  },
];

export const imageComponents = {
  astronaut1: <AstronateFirst className="astronaut-svg" />,
  astronaut2: <AstronateSecond className="astronaut-svg" />,
  // Add more mappings for other images
};
